<html><head><title></title>
<style type='text/css'> body { margin:0; padding:0;}.boldtable, .boldtable TH{font-family:Tahoma;font-size:10pt;color:white;background-color:#8DB4E2;}.boldtable TD{font-family:Tahoma;font-size:10pt;color:black;background-color:white;}</style></head><body><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px; text-align:left '>Location</th><th style='text-align:left;' >ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>HR/ PRO</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>3002</td><td style='text-align :center'>Al Nasr- Eknath Al Nasr- Eknath</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:53</td><td style='text-align :center'>05:01</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>3006</td><td style='text-align :center'>Al Nasr- Ragunath Al Nasr- Ragunath</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:43</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>3010</td><td style='text-align :center'>Security 2 Security 2</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:26</td><td style='text-align :center'>05:23</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4030</td><td style='text-align :center'>Abdul Nasar Thayyil</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>08:09</td><td style='text-align :center'>18:15</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4043</td><td style='text-align :center'>Umesh  Rai</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>07:59</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4044</td><td style='text-align :center'>Muhammad  Haj Istaefi</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>4105</td><td style='text-align :center'>Katherine Mae Palles</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:16</td><td style='text-align :center'>19:51</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Supply Chain Management</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4001</td><td style='text-align :center'>Porot  Pattillath Musthafa .</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:00</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4015</td><td style='text-align :center'>Sosimo Pepito</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>08:58</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Management</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4006</td><td style='text-align :center'>Unnikrishnan Thayyil Ramankutty Nair</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:01</td><td style='text-align :center'>17:55</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4047</td><td style='text-align :center'>Mildred Ygoña</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:39</td><td style='text-align :center'>18:04</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4092</td><td style='text-align :center'>Tarek Samir Sultan Ibrahim</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>7000</td><td style='text-align :center'>Fausto Nepote</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>7001</td><td style='text-align :center'>Rasheed Baig Baig</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:34</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>7002</td><td style='text-align :center'>Ejaz  Qadir</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>7004</td><td style='text-align :center'>Juliet Joshlyn</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>07:57</td><td style='text-align :center'>17:29</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Production</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4011</td><td style='text-align :center'>Duraisamy Raja Srinivasan .</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>07:25</td><td style='text-align :center'>17:25</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4016</td><td style='text-align :center'>John Soriano</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:35</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4028</td><td style='text-align :center'>Bernabe Gutierrez</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:36</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4032</td><td style='text-align :center'>Loganathan Muthu</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>4046</td><td style='text-align :center'>Joselito  Camacho</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:34</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4059</td><td style='text-align :center'>Sumjath Kaneeshankandy Moochikootathil </td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:23</td><td style='text-align :center'>18:36</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4063</td><td style='text-align :center'>Jafar Sadik Udinoor Valappil</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:52</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4070</td><td style='text-align :center'>Rolando Jr. Pacis</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>05:02</td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4072</td><td style='text-align :center'>Noel Flores</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:45</td><td style='text-align :center'>05:01</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4086</td><td style='text-align :center'>Pramod Kumar Madhusoodhanan Pillai Padmini Amma</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:45</td><td style='text-align :center'>05:01</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4089</td><td style='text-align :center'>Hipolito Dato</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:57</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4099</td><td style='text-align :center'>Arwin  Matanguihan</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:45</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4102</td><td style='text-align :center'>Mohammed Ismail Udinoor Valappil</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:45</td><td style='text-align :center'>05:01</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4103</td><td style='text-align :center'>Ryan Labacanacruz</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>05:00</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4104</td><td style='text-align :center'>Emmanuel Madayag</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:45</td><td style='text-align :center'>05:04</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4106</td><td style='text-align :center'>Dambarudhar Sahoo</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>07:59</td><td style='text-align :center'>17:53</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4122</td><td style='text-align :center'>Vergel Fallago</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>06:36</td><td style='text-align :center'>     </td><td style='text-align :center'></td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4123</td><td style='text-align :center'>Venugopal Naidu Ramineni</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>08:10</td><td style='text-align :center'>18:02</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4124</td><td style='text-align :center'>Sree Vankata Ramana</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>08:10</td><td style='text-align :center'>18:02</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Quality, Safety & Health Management</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4026</td><td style='text-align :center'>Sreejith Unnikrishnan</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>4115</td><td style='text-align :center'>Sherif Helmy</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:14</td><td style='text-align :center'>17:52</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Sales & proposals</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4037</td><td style='text-align :center'>Manomohan Thampuran Padaveedu</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:18</td><td style='text-align :center'>18:24</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4114</td><td style='text-align :center'>Laith Issa</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:23</td><td style='text-align :center'>19:01</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Finance</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4049</td><td style='text-align :center'>Rajish Chandran .</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:46</td><td style='text-align :center'>19:17</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>PSM</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4073</td><td style='text-align :center'>Fergus Joseph Lavers</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Engineering </td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4075</td><td style='text-align :center'>Anoop  Appukuttan</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>     </td><td style='text-align :center'>     </td><td style='text-align :center'>&#10004;</td>
<td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><tr><td style='text-align :center'>4081</td><td style='text-align :center'>Giorgio Olivieri</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:39</td><td style='text-align :center'>18:04</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><td style='text-align :center'></td><tr><td style='text-align :center'>4111</td><td style='text-align :center'>Raffaele Simeone</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>07:16</td><td style='text-align :center'>17:44</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>IT</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4088</td><td style='text-align :center'>Mohammad Shamshad Alam</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>08:00:00</td>
<td style='text-align :center'>18:00:00</td><td style='text-align :center'>08:19</td><td style='text-align :center'>17:53</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr><th  style ='width :240px;'>Business Unit</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Location</th><th>ANSALDO THOMASSEN GULF</td></tr>
<tr><th  style ='width :240px;'>Department</th><th>Quality Control Department</td></tr></table><table border=1 bordercolor=#000 cellpadding=4 cellspacing=0 style='border-collapse:collapse; width:100%;' class='boldtable'>
<tr style='height :20pt'>
<th style ='width :80px;'>Emp Code</th><th style ='width :300px;'>Employee</th><th style ='width:100px;'>Date</th style ='width:60px;'><th>Shift IN</th>
<th style ='width:60px;'>Shift OUT</th><th style ='width:65px;'>Punch IN</th><th style ='width:70px;'>Punch OUT</th><th style ='width:65px;'>Missing IN</th>
<th style ='width:76px;'>Missing OUT</th><th style ='width:55px;'>Late IN</th><th style ='width:65px;'>Late OUT</th><th>Absent</th></tr><tr><td style='text-align :center'>4116</td><td style='text-align :center'>Ratheesh Pazhani</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:45</td><td style='text-align :center'>05:01</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td><tr><td style='text-align :center'>4118</td><td style='text-align :center'>Aden Ahmed</td><td style='text-align :center'>19 Feb 17 - Sun</td><td style='text-align :center'>07:00:00</td>
<td style='text-align :center'>16:00:00</td><td style='text-align :center'>17:44</td><td style='text-align :center'>05:00</td><td style='text-align :center'></td>
<td style='text-align :center'></td><td style='text-align :center'>&#10004;</td><td style='text-align :center'>&#10004;</td><td style='text-align :center'></td></table></body></html>